name: Playwright Tests
on:
  push:
    branches:
    - main
    paths:
      - tasks/**
      - README.md*
  schedule:
  - cron: '55 * * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    permissions:
      contents: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps chromium
    - name: Run Playwright tests
      run: pnpm run start
      timeout-minutes: 10
      continue-on-error: true
    - name: update README.md
      run: pnpm run generate-readme
    - name: commit and push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # commit only if there exists changes but timestamp lines ("DTSTAMP")
        test $(git diff -U0 | grep '^[+-]' | grep -Ev '^(--- "?a/|\+\+\+ "?b/)' | grep -Ev '^(\+|-)DTSTAMP' | wc -l) = 0 || (git add . && git commit -m "chore: update calendar data")
        git push
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
